config/routes.rb
Rails.application.routes.draw do
  root to: 'items#index'
  devise_for :users
  resources :items
  resource :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :items, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :authenticate_user!, except: :index

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    current_user.items.create!(item_params)
  end

  private

  def item_params
    params.require(:item).permit(:name, :date)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @items = current_user.items
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/create.html.erb
<h1>投稿が完了しました</h1>
<%= link_to "投稿一覧へ戻る", items_path %>

app/views/items/index.html.erb
<h1>読書記録</h1>
<% if user_signed_in? %>
  <% @items.each do |item| %>
    <p><%= item.name %> : <%= item.date %>  : <%= item.user.nickname.present? ? "読者【 #{item.user.nickname}】" : "会員No.#{item.user.id}" %></p>
  <% end %>
<% else %>
  <p>ログインしてください</p>
<% end %>

app/views/items/new.html.erb
<h1>読書情報を入力</h1>
<%= form_with model: @item, local: true do |form| %>
  <p><%= form.label :name, "タイトル" %> <%= form.text_field :name %></p>
  <p><%= form.label :date, "読了日" %> <%= form.date_field :date %></p>
  <%= form.submit "登録" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LoginKadai</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= link_to "トップ", items_path %>
      <%= link_to "投稿画面へ", new_item_path %>
      <%= link_to "マイページへ", users_path %>
      <%= link_to "アカウント編集", edit_user_registration_path %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: { confirm: "ログアウトしますか？" } %>
    <% else %>
      <%= link_to "アカウント登録", new_user_registration_path %>
      <%= link_to "ログイン", new_user_session_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h1>My読書記録</h1>
<% @items.each do |item| %>
  <p><%= item.name %> : <%= item.date %></p>
<% end %>